# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install

# Rebuild bcrypt in the Docker environment
RUN npm rebuild bcrypt --build-from-source

# Install nodemon for development
RUN npm install -g nodemon

# Copy the current directory contents into the container at /app
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 4000

# Run the application when the container launches
CMD ["nodemon"]